name: Build Electron App for macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build macOS App
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build macOS App
        run: npm run build:mac

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: dist/

  delete-old-artifacts:
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
      - name: Delete old artifacts (keep latest)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            // Filter by name if needed
            const builds = artifacts.data.artifacts.filter(a => a.name === 'macOS-build');

            // Sort by created time (latest first)
            builds.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));

            // Keep the latest, delete the rest
            for (const artifact of builds.slice(1)) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              console.log(`Deleted artifact: ${artifact.name} (${artifact.id})`);
            }
